Reliabletests
ruromero/mercury pull request #2
Opened 2022-02-13 14:20 UTC by tmihalac

2022-02-14 10:09 UTC, ruromero requested changes
Just a few remarks but looks good overall, thanks.

2022-02-14 10:09 UTC, ruromero commented on mercury-api/src/main/java/com/redhat/mercury/operator/model/AbstractResourceStatus.java
> +import java.util.ArrayList;
java.util goes at the beginning

2022-02-14 10:09 UTC, ruromero commented on mercury-operator/src/main/java/com/redhat/mercury/operator/controller/AbstractController.java
> +import java.util.List;
same, fix the import order

2022-02-14 10:09 UTC, ruromero commented on mercury-operator/src/main/java/com/redhat/mercury/operator/controller/ServiceDomainClusterController.java
> +import java.util.List;
Import order

2022-02-14 10:09 UTC, ruromero commented on mercury-operator/src/main/java/com/redhat/mercury/operator/controller/ServiceDomainClusterController.java
> +                control = updateStatusWithCondition(sdc, buildReadyCondition(CONDITION_READY));
maybe you can just return the control without checking `control.isUpdateStatus()`

2022-02-14 10:09 UTC, ruromero commented on mercury-operator/src/main/java/com/redhat/mercury/operator/controller/ServiceDomainController.java
> +import java.nio.charset.StandardCharsets;
import order

2022-02-14 10:09 UTC, ruromero commented on mercury-operator/src/main/java/com/redhat/mercury/operator/controller/ServiceDomainController.java
> +    public static final String OPENAPI_CM_SUFFIX = "-openapi";
does it need to be public?

2022-02-14 10:09 UTC, ruromero commented on mercury-operator/src/main/java/com/redhat/mercury/operator/controller/ServiceDomainController.java
> +        if (sdc.getStatus() != null && sdc.getStatus().getCondition(CONDITION_READY) == null || Boolean.FALSE.toString().equalsIgnoreCase(sdc.getStatus().getCondition(CONDITION_READY).getStatus())) {
the status cannot be null

2022-02-14 10:09 UTC, ruromero commented on mercury-operator/src/main/java/com/redhat/mercury/operator/controller/ServiceDomainController.java
> +                if (sdConfigMap == null) {
All the integration checks should be part of the createOrUpdateIntegration, create submethods if necessary

2022-02-16 09:06 UTC, tmihalac commented on mercury-operator/src/main/java/com/redhat/mercury/operator/controller/ServiceDomainController.java
> +    public static final String OPENAPI_CM_SUFFIX = "-openapi";
Using it in the test

2022-02-16 11:42 UTC, ruromero approved these changes

2022-02-16 11:43 UTC, merged